---
  - name: Check wordress installed or not
    stat:
      path: "{{ wordpress_install_path }}wp-config.php"
    register: wp_existence

  - name: Download and Unzip wordpress 
    get_url: 
       url: "{{ wordpress_download_url }}"
       dest: "{{ wordpress_install_path }}"
    register: wordpress_file

  - set_fact: wp_file="{{ wordpress_file.dest }}"
  
  - name: Download and Unzip wordpress 
    unarchive: 
       src: "{{ wordpress_file.dest }}"
       dest: "{{ wordpress_install_path }}"
       extra_opts: ['--strip-components=1', '--show-stored-names']
       remote_src: yes

  - name: Copy config file
    template:
      src: wp-config.php.j2
      dest: "{{ wordpress_install_path }}/wp-config.php"

    
